#
# Copyright (c) 2018-2019 Intel Corporation.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#
# This represents the target speed/accel values of the ego vehicle

float32 steering_angle
float32 speed
float32 speed_abs
float32 accel
float32 jerk


#float32 steering_angle //转向角
#float32 steering_angle_velocity //转向角的速度
#float32 speed //向前的速度
#float32 acceleration //加速度
#float32 jerk //变加速度

